version: "3.6"

services:
  mongo:
    image: mongo:8.0.3
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    volumes:
      - etcd_data:/bitnami/etcd

  indexer_withdrawal_requests:
    image: quay.io/apibara/sink-mongo:0.9.3
    depends_on:
      - etcd
    restart: always
    ports:
      - "8001:8001"
    command:
      - run
      - --allow-env=/data/env
      - /data/src/id_owners.ts
      - --status-server-address=0.0.0.0:8001
    volumes:
      - ./:/data/
    environment:
      PERSIST_TO_ETCD: http://etcd:2379
      SINK_ID: withdrawal_requests
      AUTH_TOKEN: dna_xxx

volumes:
  etcd_data:
  mongo_data:
